version: '3.4'

services:
  owncloud:
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.backend=owncloud"
      - "traefik.frontend.rule=Host:${OWNCLOUD_DOMAIN}"
      - "traefik.port=8080"

  traefik:
    image: traefik:v1.7-alpine
    restart: always
    ports:
      - ${TRAEFIK_HTTPS_PORT:-443}:443
      - ${TRAEFIK_HTTP_PORT:-80}:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./reverse-proxy/traefik/traefik.toml:/traefik.toml:ro
      - ./reverse-proxy/traefik/acme:/etc/traefik/acme
