version: '3.4'

services:
  owncloud:
    depends_on:
      - db
    environment:
      - OWNCLOUD_DB_TYPE=oci
      - OWNCLOUD_DB_NAME=XE
      - OWNCLOUD_DB_HOST=db
      - OWNCLOUD_DB_USERNAME=autotest
      - OWNCLOUD_DB_PASSWORD=owncloud
    volumes:
     - ./database/oracle-wait-for-database.sh:/etc/pre_install.d/00-oracle-wait-for-database.sh
  db:
    # alternative tag 12.2.0.1-slim
    image: deepdiver/docker-oracle-xe-11g
    environment:
      - ORACLE_DISABLE_ASYNCH_IO=true