### DOCKER FILE FOR eos/mq IMAGE BASED ON EOS CITRINE -- EOS 4.x Version ###

FROM eos/base

MAINTAINER David Jericho <david.jericho@aarnet.edu.au>
MAINTAINER Crystal Chua <crystal.chua@aarnet.edu.au>

# ----- Copy some scripts so we can run them ----- #
COPY containers/content/scripts/entrypoint.mq /entrypoint
