#!/bin/bash

function gracefulShutdown {
  echo "Shutting down gracefully!"
  umount -f ${EOS_FUSE_MOUNTDIR}
  killall -KILL eosd
  umount -f ${EOS_FUSE_MOUNTDIR}
  exit
}

cat /etc/eos/fuse.conf.tmp | jq --arg host ${EOS_FUSE_MGM_ALIAS-localhost}:${MGM_PORT-1094} '.hostport |= $host' > /etc/eos/fuse.conf

exec eosxd -f
