version: '3.7'

volumes:
  files:
    driver: local
  etcd_data:
    driver: local
  build:
    driver: local

services:
  etcd:
    image: bitnami/etcd:3
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    volumes:
      - etcd_data:/bitnami/etcd

  micro:
    env_file: .global.env
    image: micro/micro
    ports:
      - 8080:8080
      - 8082:8082
    command:
      server

  accounts:
    env_file: .global.env
    image: owncloud/ocis-accounts:latest
    environment:
      - ACCOUNTS_ADDRESS=0.0.0.0:9180
    volumes: 
      - files:/ocis-data

  add-user:
    env_file: .global.env
    build:
      context: ./add-user
    image: add-user
    volumes:
      - build:/go/pkg

  list-nodes:
    env_file: .global.env
    build:
      context: ./list-nodes
    image: list-nodes
    volumes:
      - build:/go/pkg
