version: '3.7'

volumes:
  files:
    driver: local
  mysql:
    driver: local
  backup:
    driver: local
  redis:
    driver: local
  tmp:
    driver: local

services:
  owncloud:
    build:
      context: ./owncloud
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    expose:
      - "8080"
    depends_on:
      - db
      - redis
    environment:
      - OWNCLOUD_DOMAIN=${OWNCLOUD_DOMAIN}
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=owncloud
      - OWNCLOUD_DB_HOST=db
      - OWNCLOUD_ADMIN_USERNAME=admin
      - OWNCLOUD_ADMIN_PASSWORD=admin
      - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis
      #- OWNNCLUD_APPS_INSTALL=https://github.com/owncloud/data_exporter/releases/download/v0.2.0/data_exporter-0.2.0.tar.gz
      - OWNCLOUD_APPS_ENABLE=openidconnect,oauth2,data_exporter
      - OWNCLOUD_LOG_LEVEL=0
    volumes:
      - files:/mnt/data
      - tmp:/tmp/shared
  ocis:
    image: owncloud/ocis:latest
    build:
      context: ./ocis
      dockerfile: Dockerfile
    depends_on:
      - ocis-accounts
    ports:
      - 9200:9200
    expose:
      - "9130"
    environment:
      - OCIS_LOG_LEVEL=debug
      - OCIS_CONFIG_FILE=/config/proxy-config.json
      - PROXY_TRANSPORT_TLS_CERT=/proxy_certs/localhost.crt
      - PROXY_TRANSPORT_TLS_KEY=/proxy_certs/localhost.key
      - KONNECTD_VALIDATION_KEYS_PATH=/konnectd_keys/
      - KONNECTD_SIGNING_PRIVATE_KEY=/konnectd_keys/private-key.pem
      - KONNECTD_ENCRYPTION_SECRET=/konnectd_keys/encryption.key
      - KONNECTD_TLS=0
    volumes:
      - ./ocis/proxy-config.json:/config/proxy-config.json
      - ./ocis/identifier-registration.yml:/config/identifier-registration.yml
      - tmp:/tmp/shared

  ocis-accounts:
    image: owncloud/ocis-accounts:latest

  db:
    image: webhippie/mariadb:latest
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=owncloud
      - MARIADB_USERNAME=owncloud
      - MARIADB_PASSWORD=owncloud
      - MARIADB_DATABASE=owncloud
      - MARIADB_MAX_ALLOWED_PACKET=128M
      - MARIADB_INNODB_LOG_FILE_SIZE=64M
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - mysql:/var/lib/mysql
      - backup:/var/lib/backup

  redis:
    image: webhippie/redis:latest
    environment:
      - REDIS_DATABASES=1
    volumes:
      - redis:/var/lib/redis