version: '3.4'

services:
  owncloud:
    environment:
      - BROWSER=firefox
      - SRV_HOST_PORT=80
      - SRV_HOST_NAME=owncloud
      - SELENIUM_PORT=4444
      - SELENIUM_HOST=selenium_firefox_standalone


  selenium_firefox_standalone:
    image: selenium/standalone-firefox:${FIREFOX_SELENIUM_VERSION:-latest}
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - SE_OPTS=-enablePassThrough false
