#!/bin/sh
echo "Waiting for LDAP ..."
until nc -z -w 3 ldap.testnet 389; do sleep 1; done;
echo "LDAP server is online"

# set variables
. /etc/sysconfig/eos
XRD_COREDIR="/var/spool/eos/core"
EOS_MQ_MASTER_FILE="/var/eos/eos.mq.master"
PATH=$PATH:/sbin

# remove all ipv6
sed '/ip6/d' /etc/hosts > /etc/tmphosts && cat /etc/tmphosts > /etc/hosts && rm -f /etc/tmphosts && cat /etc/hosts
sed '/localhost6/d' /etc/hosts > /etc/tmphosts && cat /etc/tmphosts > /etc/hosts && rm -f /etc/tmphosts && cat /etc/hosts

chown -R daemon:daemon /var/eos/

# check if this node is a master - if so, create the relevant file
if [ "z${EOS_SET_MASTER}" = "ztrue" ] || [ ${EOS_SET_MASTER} -eq 1 ]; then
    touch ${EOS_MQ_MASTER_FILE}
fi

# check if we should use quarkdb, if so set correct config
if [ "${EOS_USE_QDB}" = "true" ] || [ "${EOS_USE_QDB}" = 1 ]; then
  # remove potential duplicate lines from mq config
  sed -i '/mqofs.qdbcluster/d' /etc/xrd.cf.mq
  sed -i '/mqofs.qdbpassword_file/d' /etc/xrd.cf.mq
  echo "mqofs.qdbcluster ${EOS_QDB_NODES}" >> /etc/xrd.cf.mq
  echo "mqofs.qdbpassword_file /etc/eos.client.keytab" >> /etc/xrd.cf.mq
fi

# start mq
mkdir -p ${XRD_COREDIR} && chown daemon:daemon ${XRD_COREDIR}
echo "Starting mq for " $(rpm -q eos-server | sed s/eos-server-//g)
cd ${XRD_COREDIR}

XRDPROG=/usr/bin/xrootd
test -e /opt/eos/xrootd/bin/xrootd && XRDPROG=/opt/eos/xrootd/bin/xrootd

exec $XRDPROG -n mq -c /etc/xrd.cf.mq -Rdaemon

# chown -R daemon:daemon /var/log/eos/
# exec $XRDPROG -n mq -c /etc/xrd.cf.mq -l /var/log/eos/mq/xrdlog.mq -Rdaemon
