#!/bin/sh

# todo: log all ocis services to stdout

echo "Waiting for EOS MGM"
echo "until nc -z -w 3 $EOS_MGM_ALIAS 1094; do sleep 2; done;" > /wait-for-mgm
chmod +x /wait-for-mgm

/wait-for-mgm
sleep 5

echo "----- LDAP setup -----"
authconfig --enableldap --enableldapauth --ldapserver=${EOS_LDAP_HOST} --ldapbasedn="dc=example,dc=org" --update
sed -i "s/#binddn cn=.*/binddn cn=reva,ou=sysusers,dc=example,dc=org/" /etc/nslcd.conf
sed -i "s/#bindpw .*/bindpw reva/" /etc/nslcd.conf
nslcd

sleep 5

eos -r 0 0 -b vid set membership daemon -uids adm
eos -r 0 0 -b vid set membership daemon -gids adm
eos -r 0 0 -b vid set membership daemon +sudo
eos -r 0 0 -b vid set map -unix "<pwd>" vuid:0 vgid:0
# eos -r 0 0 -b vid add gateway ocis.testnet
eos -r 0 0 -b vid add gateway ocis

echo "----- DOMAIN setup -----"
echo "Domain / IP: $OCIS_DOMAIN"
mkdir -p /etc/ocis
sed -e "s|@IPADDR@|${OCIS_DOMAIN}|g" /config/identifier-registration.yml.tmpl > /etc/ocis/identifier-registration.yml

echo "----- Starting oCIS -----"
ocis reva-storage-home &
ocis reva-storage-home-data &
ocis reva-storage-eos &
    
ocis reva-storage-eos-data &
ocis micro &
ocis glauth &
ocis graph-explorer &
ocis graph &
ocis konnectd &
ocis phoenix &
ocis thumbnails &
ocis webdav &
ocis reva-auth-basic &
ocis reva-auth-bearer &
ocis reva-frontend &
ocis reva-gateway &
ocis reva-sharing &
ocis reva-users &
ocis proxy