version: '3.4'

services:
  owncloud:
    depends_on:
      - samba

  samba:
    image: owncloudci/samba:${SAMBA_CONTAINER_TAG:-latest}
    command: "-u \"user1;user1pass\" -u \"user2;user2pass\" -s \"tmp;/tmp;yes;no;no;user1,user2;none;user1,user2\" -S"