FROM owncloud/server:latest
ADD apps/openidconnect-0.2.0.tar.gz /var/www/owncloud/apps/
ADD apps/oauth2-0.4.4RC1.tar.gz /var/www/owncloud/apps/
ADD apps/graphapi-0.1.0.tar.gz /var/www/owncloud/apps/
COPY overlay /
