#!/bin/bash

docker build -t eos/base ./eos-base
docker build -t eos/mq ./eos-mq
docker build -t eos/mgm ./eos-mgm
docker build -t eos/fst ./eos-fst
docker build -t eos/qdb ./eos-qdb
docker build -t eos/ocis ./eos-ocis

# docker build -t eos/eosd ./eos-eosd
# docker build -t eos/eosxd ./eos-eosxd