#!/bin/sh
echo "Waiting for LDAP ..."
until nc -z -w 3 ldap.testnet 389; do sleep 1; done;
echo "LDAP server is online"

# remove all ipv6
sed '/ip6/d' /etc/hosts > /etc/tmphosts && cat /etc/tmphosts > /etc/hosts && rm -f /etc/tmphosts && cat /etc/hosts
sed '/localhost6/d' /etc/hosts > /etc/tmphosts && cat /etc/tmphosts > /etc/hosts && rm -f /etc/tmphosts && cat /etc/hosts

# dynamicly config based on env variables
QDB_CONF=/etc/xrd.cf.qdb
if [ "${EOS_QDB_PORT}" ]; then
  sed -i '/xrd.port/d' ${QDB_CONF}
  sed -i '/xrd.protocol/d' ${QDB_CONF}
  echo "xrd.port ${EOS_QDB_PORT}"                                       >> ${QDB_CONF}
  echo "xrd.protocol redis:${EOS_QDB_PORT} /usr/lib64/libXrdQuarkDB.so" >> ${QDB_CONF}
fi
if [ "${EOS_QDB_DIR}" ]; then
  sed -i '/redis.database/d' ${QDB_CONF}
  echo "redis.database ${EOS_QDB_DIR}"                                  >> ${QDB_CONF}
fi
if [ "${EOS_QDB_MODE}" ]; then
  sed -i '/redis.mode/d' ${QDB_CONF}
  echo "redis.mode ${EOS_QDB_MODE}"                                     >> ${QDB_CONF}
fi
if ! [ "${EOS_QDB_MODE}" = "bulkload" ]; then
  sed -i '/redis.password_file/d' ${QDB_CONF}
  echo "redis.password_file /etc/eos.client.keytab"                   >> ${QDB_CONF}
fi
if [ "${EOS_QDB_MODE}" = "raft" ]; then
  sed -i '/redis.myself/d' ${QDB_CONF}
  echo "redis.myself `hostname -f`:${EOS_QDB_PORT}"                   >> ${QDB_CONF}
fi

# create quarkdb database folder if it doesn't exist
if ! [ -d "${EOS_QDB_DIR}" ]; then
  if [ "${EOS_QDB_MODE}" = "raft" ]; then
    quarkdb-create --path ${EOS_QDB_DIR} --clusterID ${EOS_QDB_CLUSTER_ID} --nodes ${EOS_QDB_NODES}
  else
    quarkdb-create --path ${EOS_QDB_DIR}
  fi
else
  if [ "${EOS_QDB_MODE}" = "raft" ] && ! [ -d "${EOS_QDB_DIR}/current/raft-journal" ]; then
    quarkdb-journal --create --path ${EOS_QDB_DIR}/current/raft-journal --clusterID ${EOS_QDB_CLUSTER_ID} --nodes ${EOS_QDB_NODES}
  fi
fi
chown -R daemon:daemon ${EOS_QDB_DIR}

XRDPROG=/usr/bin/xrootd
test -e /opt/eos/xrootd/bin/xrootd && XRDPROG=/opt/eos/xrootd/bin/xrootd

exec $XRDPROG -R daemon -n quarkdb -c /etc/xrd.cf.qdb

# chown -R daemon:daemon /var/log/eos/
# exec $XRDPROG -R daemon -n quarkdb -c /etc/xrd.cf.qdb -l /var/log/eos/qdb/xrdlog.qdb