#!/bin/sh

# set variables
. /etc/sysconfig/eos
XRD_COREDIR="/var/spool/eos/core"
EOS_MGM_MASTER_FILE="/var/eos/eos.mgm.rw"
PATH=$PATH:/sbin

# remove all ipv6
sed '/ip6/d' /etc/hosts > /etc/tmphosts && cat /etc/tmphosts > /etc/hosts && rm -f /etc/tmphosts && cat /etc/hosts
sed '/localhost6/d' /etc/hosts > /etc/tmphosts && cat /etc/tmphosts > /etc/hosts && rm -f /etc/tmphosts && cat /etc/hosts


mkdir -p /var/eos/tx /var/eos/auth /var/eos/config /var/eos/md /var/eos/archive /var/eos/ns-queue /var/eos/report
# try to fix socket permissions in md folder, when mounted - untested
# python -c "import socket as s; sock = s.socket(s.AF_UNIX); sock.bind('/var/eos/md/.admin_socket:1094')"
chown -R daemon:daemon /var/eos/tx /var/eos/auth /var/eos/config /var/eos/md /var/eos/archive /var/eos/ns-queue /var/eos/report

mkdir -p /var/log/eos/tx /var/log/eos/mgm
chown -R daemon:daemon /var/log/eos/

# check if this node is a master - if so, create the relevant file
if [ "${EOS_SET_MASTER}" = "true" ] || [ "${EOS_SET_MASTER}" = 1 ]; then
    touch ${EOS_MGM_MASTER_FILE}
    chown daemon:daemon ${EOS_MGM_MASTER_FILE}
fi

# check if we should use quarkdb, otherwise default to in-memory namespace
if [ "${EOS_USE_QDB}" = "true" ] || [ "${EOS_USE_QDB}" = 1 ]; then
  sed -i '/mgmofs.nslib/d' /etc/xrd.cf.mgm
  sed -i '/mgmofs.qdbcluster/d' /etc/xrd.cf.mgm
  sed -i '/mgmofs.qdbpassword_file/d' /etc/xrd.cf.mgm
  sed -i '/mgmofs.centraldrain/d' /etc/xrd.cf.mgm
  echo "mgmofs.nslib /usr/lib64/libEosNsQuarkdb.so" >> /etc/xrd.cf.mgm
  echo "mgmofs.qdbcluster ${EOS_QDB_NODES}" >> /etc/xrd.cf.mgm
  echo "mgmofs.qdbpassword_file /etc/eos.client.keytab" >> /etc/xrd.cf.mgm
  echo "mgmofs.centraldrain true" >> /etc/xrd.cf.mgm
else
  sed -i '/mgmofs.nslib/d' /etc/xrd.cf.mgm
  echo "mgmofs.nslib /usr/lib64/libEosNsInMemory.so" >> /etc/xrd.cf.mgm
fi

if [ "${EOS_USE_QDB_CONFIG}" = "true" ] || [ "${EOS_USE_QDB_CONFIG}" = 1 ]; then
  sed -i '/mgmofs.cfgtype/d' /etc/xrd.cf.mgm
  echo "mgmofs.cfgtype quarkdb" >> /etc/xrd.cf.mgm
else
  sed -i '/mgmofs.cfgtype/d' /etc/xrd.cf.mgm
  echo "mgmofs.cfgtype file" >> /etc/xrd.cf.mgm
fi

echo "----- Planning setup -----"
echo "until nc -z -w 3 localhost 1094; do sleep 1; done;" > /wait-for-mgm
chmod +x /wait-for-mgm

(/wait-for-mgm; ./setup > /var/log/eos/mgm/eos.setup.log; cat /var/log/eos/mgm/eos.setup.log) &

# start mgm
echo "Starting mgm for " $(rpm -q eos-server | sed s/eos-server-//g)
mkdir -p ${XRD_COREDIR} && chown daemon:daemon ${XRD_COREDIR}
cd ${XRD_COREDIR}

# export EOS_BROKER_URL="root://mgm-master.testnet:1097//eos/"
export EOS_START_SYNC_SEPARATELY=1

XRDPROG=/usr/bin/xrootd
test -e /opt/eos/xrootd/bin/xrootd && XRDPROG=/opt/eos/xrootd/bin/xrootd

exec $XRDPROG -R daemon -n mgm -c /etc/xrd.cf.mgm 

# exec $XRDPROG -R daemon -n mgm -c /etc/xrd.cf.mgm -l /var/log/eos/xrdlog.mgm
# has to write into logfile: /var/log/eos/xrdlog.mgm or will die - no idea why
